spring.application.name=demo1

#spring.data.mongodb.uri=mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@cluster0.z0pwmvn.mongodb.net/${MONGODB_BASE}?retryWrites=true&w=majority&appName=Cluster0

spring.data.mongodb.uri=mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@cluster0.ypoimvw.mongodb.net/${MONGODB_BASE}?retryWrites=true&w=majority&appName=Cluster0

